### ISSUE TITLE
Is the AWS project still up?

### ISSUE THREAD

**Issue by cjcarlson** [serratus-bio/tantalus#3]
Getting this error message when I try to run the R package:

```
> library("tantalus")
> library("dbplyr")
> library("RPostgreSQL") 
> 
> drv <- DBI::dbDriver("PostgreSQL")
> con <- DBI::dbConnect(drv, 
+                       user="postgres", 
+                       password="serratus",
+                       host="big-parse-db.ccz9y6yshbls.us-east-1.rds.amazonaws.com", 
+                       port=5432, 
+                       dbname="postgres")

Error in postgresqlNewConnection(drv, ...) : 
  RS-DBI driver: (could not connect postgres@big-parse-db.ccz9y6yshbls.us-east-1.rds.amazonaws.com:5432 on dbname "postgres": could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host "big-parse-db.ccz9y6yshbls.us-east-1.rds.amazonaws.com" (3.223.101.173) and accepting
	TCP/IP connections on port 5432?
```

**Comment by ababaian** [comment]
Hey Colin,

Sorry I just saw this, the server is online yes (website is working). Let me take a look at what can be going on. The other option is to directly access the postgreSQL server with `pgadmin4`.

**Comment by cjcarlson** [comment]
Thanks Artem! Yeah, just let me know - I think I'm finally starting to wrap my mind around how to interact the Serratus data with what we're building

**Comment by ababaian** [comment]
Let me know how we can help [ : ) ](https://youtu.be/4cia_v4vxfE?t=44)

**Comment by cjcarlson** [comment]
We've tried this on a few machines and it's definitely not a local problem. Can you check if the ports are open to web traffic / the correct subnets are connected? (Or just, otherwise check if the API endpoint is working?) I'm hoping specifically to use tantalus rather than pgadmin4 if at all possible

**Comment by victorlin** [comment]
@cjcarlson there was some AWS configuration issue – I moved the DB to a new VPC and it should work now. Could you try again?

**Comment by ababaian** [comment]
Works on my end. Thanks @victorlin!!

**Comment by cjcarlson** [comment]
Hey gang - I only get part of the way. I can run the `con` code now but


> sras <- c("SRR5447167")
> sras
[1] "SRR5447167"
> serr <- getSummaryFiles(sras, 's3://lovelywater/summary/', "C:/Users/cjcar/Desktop/sra")
[1] "aws s3 cp s3://lovelywater/summary/SRR5447167.summary C:/Users/cjcar/Desktop/sra/"
fatal error: Unable to locate credentials

@victorlin thoughts?

**Comment by ababaian** [comment]
Can you run `aws s3 cp s3://lovelywater/summary/SRR5447167.summary ./` from your command line successfully? The simple answer is you need to have your AWS CLI configured with an account on your system. This is simply running `aws configure` from the command line and inputting your credentials.

Alternatively you can jimmy the code to add `--no-sign-request` to the commands such as `aws s3 cp s3://lovelywater/summary/SRR5447167.summary ./ --no-sign-request` and avoid since we do allow full public access.

The last option is to just use `wget` on those files such as `wget https://lovelywater.s3.amazonaws.com/summary/SRR5447167.summary`. This will bypass aws-cli completely.

If you can open this as a seperate issue I'll deal with it when we re-factor the code. We're working on an overhaul at the moment and most of the code needs to be re-written anyways so I can add this then.

**Comment by cjcarlson** [comment]
Hey @ababaian - yep, I can run that from command line successfully - seems like an issue on the R side.

**Comment by ababaian** [comment]
:+1: Can you open a seperate issue for this and I'll swing back to it with the code-refactoring.
